[package]
name = "MetaMix Studio Core"
version = "0.1.0"
authors = ["jdeepee <joshuadparkin@gmail.com>"]
edition = "2019"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "*"
stdweb = "*"
phf = { version = "0.7.24", features = ["macros"] }